fix: Correct handling for 0-dim arrays.
stan-dev/pystan pull request #227
Opened 2021-02-26 12:53 UTC by ahartikainen

Return empty array with correct shape for 0-dim arrays.

This PR is related to https://github.com/stan-dev/httpstan/pull/547

2021-02-26 15:28 UTC, riddell-stan commented
This will need tests. I think we need at least
- [ ] One test which has a zero-length vector (or similar).
- [ ] One test which involves a zero-length vector (or similar) and a non-zero-length vector.

2021-03-22 23:15 UTC, ahartikainen commented
This works with the current github httpstan/main.

I added a test that tests against 1D, 2D stan arrays, stan vector and stan matrix and a stan array of stan matrices.

After httpstan is updated to pypi, we can make this a PR and test.

2021-03-22 23:56 UTC, riddell-stan commented on stan/fit.py
> +        return view
```suggestion
        if not len(param_indexes):
            return np.empty(param_dim + [num_samples_saved * self.num_chains])
        view = self._draws[param_indexes, :, :].reshape(len(param_indexes), -1).view()
        assert view.shape == (len(param_indexes), num_samples_saved * self.num_chains)
        # reshape must yield something with least two dimensions
        reshape_args = param_dim + [-1] if param_dim else (1, -1)
        # reshape, recover the shape of the stan parameter
        return view.reshape(*reshape_args, order="F")
```
Two fewer lines and easier to read, I think.

I might add a comment right after the `if` statement and explain that a zero-length parameter is involved.

Also, Surely the `np.empty` is wrong? That's just going to be random data (uninitialized memory).

2021-03-24 08:27 UTC, ahartikainen commented on stan/fit.py
> +        return view
I think `np.empty` is fine, it is 0-dimensional object containing nothing.

2021-03-24 12:20 UTC, riddell-stan requested changes

2021-03-24 12:20 UTC, riddell-stan commented on stan/fit.py
> +            return np.empty(param_dim + [num_samples_saved * self.num_chains])
```suggestion
            assert 0 in param_dim
            return np.array([]).reshape(param_dim + [num_samples_saved * self.num_chains])
```

I prefer this because `np.empty` has strong connotations of allocating space, just like `np.ones` and `np.zeros`. Also there is a confusion between two senses of the word `empty`.

2021-03-24 12:41 UTC, ahartikainen commented on stan/fit.py
> +            return np.empty(param_dim + [num_samples_saved * self.num_chains])
That solution looks good too. I can change the code.

2021-03-24 15:55 UTC, riddell-stan approved these changes

2021-03-24 16:02 UTC, merged