ci: Add debian bullseye to matrix
stan-dev/pystan pull request #303
Opened 2021-05-21 12:14 UTC by riddell-stan

Add debian bullseye to matrix.

2021-05-21 12:54 UTC, ahartikainen approved these changes

2021-05-21 13:49 UTC, riddell-stan commented
I'm having a hard time telling if the container is actually being used. It wasn't clear from a quick glance at the log.

2021-05-21 17:27 UTC, riddell-stan commented
@ahartikainen any interest in taking a stab at fixing this -- i.e., getting testing working in these different containers? I think some modest additions to our GitHub Actions workflow will be required.

2021-05-21 19:17 UTC, ahartikainen requested changes
This can be used to check version

    cat /etc/os-release

(It only works on Linux).

Also, there is a container setup step in the workflow log, which shows what system is used.

2021-05-21 19:17 UTC, ahartikainen commented on .github/workflows/main.yml
>          run: pip install "poetry~=1.1.4"
```suggestion
        run: python3 -m pip install "poetry~=1.1.4"
```

2021-05-21 19:17 UTC, ahartikainen commented on .github/workflows/main.yml
>            - {runs-on: ubuntu-20.04, container: "ubuntu:latest", python-version: 3.8}
```suggestion
```

2021-05-21 19:17 UTC, ahartikainen commented on .github/workflows/main.yml
>            - {runs-on: ubuntu-20.04, container: "ubuntu:latest", python-version: 3.8}
Apparently this image needs a bunch of configuration to get it working. (Can not install anything from pip due to some SSL problem)

2021-05-21 19:18 UTC, ahartikainen commented on .github/workflows/main.yml
>          run: pip install "poetry~=1.1.4"
Those containers are missing `pip` in the main namespace.

2021-05-23 14:44 UTC, riddell-stan commented
I think we should abandon this. It's enough to officially support Ubuntu 20.04 and higher and Debian 11 and higher. (Debian 11 is essentially the same as Ubuntu 21.04.)

I'll add a FAQ item about other distributions which have been reported as working. We can mention Fedora 34 there, for example.

2021-05-23 14:44 UTC, closed without merging